version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_path:/bundle
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /bundle/vendor
    command: bash entrypoints/start.sh

  postgres:
    image: postgres:13.6
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:5.0.7
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - postgres
      - redis
      - mongodb
    volumes:
      - .:/app
      - bundle_path:/bundle
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /bundle/vendor
    command: bash entrypoints/start_jobs.sh

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - shared_database:/data/db

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  bundle_path:
  db_data:
  node_modules:
  shared_database:
