version: '3'

services:
  db:
    image: 'postgres:13.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  test:
    depends_on:
      - 'db'
      - 'selenium'
    build: .
    command: bash entrypoints/start.sh
    volumes:
      - '.:/app'
      - 'box:/box'
      - bundle_path:/bundle
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=test
      - TEST_PORT=3000
      - RAILS_ENV=test
      - BUNDLE_PATH=/bundle/vendor
    stdin_open: true
    tty: true

  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    logging:
      driver: none
    stdin_open: true
    tty: true
    ports: [ '4444:4444', '5900:5900' ]

  box:
    image: busybox
    volumes:
      - box:/box

volumes:
  postgres:
  box:
  bundle_path:
