docker-compose exec app bundle exec rails g scaffold IndividualRegistration \
cns_cpf_cidadao:string \
cns_cpf_responsavel_familiar:string \
nome_completo:string \
data_nascimento:date \
sexo:string \
raca_cor:string \
etnia:string \
pis_pasep:string \
nome_completo_mae:string \
nome_completo_pai:string \
nacionalidade:string \
pais_nascimento:date \
data_naturalizacao:string \
municipio_uf_nascimento:string \
telefone_celular:string \
email:string \
relacao_parentesco_responsavel_familiar:string \
curso_elevado_frequenta_frequentou:string \
situacao_mercado_trabalho:string \
frequenta_cuidador_tradicional:string \
participa_grupo_comunitario:string \
possui_plano_saude_privado:string \
orientacao_sexual:string \
identidade_genero:string \
saida_cidadao_cadastro:string \
gestante:string \
peso:string \
fumante:string \
uso_alcool:string \
uso_outras_drogas:string \
hipertensao_arterial:string \
diabetes:string \
avc_derrame:string \
infarto:string \
hanseniase:string \
tuberculose:string \
tem_ou_teve_cancer:string \
alguma_internacao_ultimos_12_meses:string \
diagnostico_algum_problema_saude_mental_profissional_saude:string \
acamado:string \
domiciliado:string \
outras_praticas_integrativas_complementares:string \
situacao_rua:string \
recebe_algum_beneficio:string \
possui_referencia_familiar:string
