# frozen_string_literal: true
class CreateIndividualRegistrations < ActiveRecord::Migration[6.1]
  def change
    create_table(:individual_registrations) do |t|
      t.boolean(:statusTemDoencaRespiratoria, null: true)
      t.boolean(:statusUsaOutrasPraticasIntegrativasOuComplementares, null: true)
      t.boolean(:statusTemTeveDoencasRins, null: true)
      t.boolean(:statusTeveDoencaCardiaca, null: true)
      t.boolean(:statusTeveInternadoEm12Meses, null: true)
      t.boolean(:statusUsaPlantasMedicinais, null: true)
      t.string(:grauParentescoFamiliarFrequentado, null: true)
      t.string(:nomeSocial, null: true)
      t.integer(:higienePessoalSituacaoRua, array: true, default: [])
      t.integer(:origemAlimentoSituacaoRua, array: true, default: [])
      t.string(:outraInstituicaoQueAcompanha, null: true)
      t.integer(:quantidadeAlimentacoesAoDiaSituacaoRua, null: true)
      t.boolean(:statusAcompanhadoPorOutraInstituicao, null: true)
      t.boolean(:statusTemAcessoHigienePessoalSituacaoRua, null: true)
      t.boolean(:statusVisitaFamiliarFrequentemente, null: true)
      t.integer(:tempoSituacaoRua, null: true)
      t.string(:codigoIbgeMunicipioNascimento, null: true)
      t.boolean(:desconheceNomeMae, null: true)
      t.boolean(:statusEhResponsavel, null: true)
      t.string(:nomePaiCidadao, null: true)
      t.boolean(:desconheceNomePai, null: true)
      t.string(:dtNaturalizacao, null: true)
      t.string(:dtEntradaBrasil, null: true)
      t.string(:microArea, null: true)
      t.boolean(:stForaArea, null: true)
      t.integer(:deficienciasCidadao, array: true, default: [])
      t.integer(:responsavelPorCrianca, array: true, default: [])
      t.integer(:grauInstrucaoCidadao, null: true)
      t.string(:ocupacaoCodigoCbo2002, null: true)
      t.string(:portariaNaturalizacao, null: true)
      t.boolean(:statusFrequentaEscola, null: true)
      t.boolean(:statusMembroPovoComunidadeTradicional, null: true)
      t.boolean(:statusDesejaInformarIdentidadeGenero, null: true)
      t.string(:coPovoComunidadeTradicional, null: true)
      t.uuid(:uuid)
      t.uuid(:uuidFichaOriginadora, null: true)
      t.string(:profissionalCNS)
      t.string(:cboCodigo_2002)
      t.string(:cnes)
      t.string(:ine)
      t.datetime(:dataAtendimento)
      t.string(:codigoIbgeMunicipio)
      t.uuid(:uuidDadoSerializado)
      t.integer(:tipoDadoSerializado)
      t.string(:codIbge)
      t.string(:cnesDadoSerializado)
      t.string(:ineDadoSerializado)
      t.integer(:numLote)
      t.boolean(:fichaAtualizada)
      t.boolean(:motivoSaidaCidadao, null: true)
      t.integer(:tpCdsOrigem, null: true)
      t.string(:descricaoCausaInternacaoEm12Meses, null: true)
      t.string(:descricaoOutraCondicao1, null: true)
      t.string(:descricaoOutraCondicao2, null: true)
      t.string(:descricaoOutraCondicao3, null: true)
      t.string(:descricaoPlantasMedicinaisUsadas, null: true)
      t.integer(:doencaCardiaca, array: true, default: [])
      t.integer(:doencaRespiratoria, array: true, default: [])
      t.integer(:doencaRins, array: true, default: [])
      t.string(:maternidadeDeReferencia, null: true)
      t.integer(:situacaoPeso, null: true)
      t.boolean(:statusEhDependenteAlcool, null: true)
      t.boolean(:statusEhDependenteOutrasDrogas, null: true)
      t.boolean(:statusEhFumante, null: true)
      t.boolean(:statusEhGestante, null: true)
      t.boolean(:statusEstaAcamado, null: true)
      t.boolean(:statusEstaDomiciliado, null: true)
      t.boolean(:statusTemDiabetes, null: true)
      t.boolean(:statusTemHanseniase, null: true)
      t.boolean(:statusTemHipertensaoArterial, null: true)
      t.boolean(:statusTemTeveCancer, null: true)
      t.boolean(:statusTemTuberculose, null: true)
      t.boolean(:statusTeveAvcDerrame, null: true)
      t.boolean(:statusTeveInfarto, null: true)
      t.boolean(:statusDiagnosticoMental, null: true)
      t.boolean(:statusPossuiReferenciaFamiliar, null: true)
      t.boolean(:statusRecebeBeneficio, null: true)
      t.boolean(:statusSituacaoRua, null: true)
      t.string(:dataNascimentoCidadao, null: false)
      t.string(:emailCidadao, null: true)
      t.integer(:nacionalidadeCidadao, null: false)
      t.string(:nomeCidadao, null: false)
      t.string(:nomeMaeCidadao, null: true)
      t.string(:cpfCidadao, null: true)
      t.string(:cpfResponsavelFamiliar, null: true)
      t.string(:cnsCidadao, null: true)
      t.string(:cnsResponsavelFamiliar, null: true)
      t.string(:telefoneCelular, null: true)
      t.string(:numeroNisPisPasep, null: true)
      t.integer(:paisNascimento, null: true)
      t.integer(:racaCorCidadao, null: false)
      t.integer(:sexoCidadao, null: false)
      t.integer(:etnia, null: true)
      t.integer(:orientacaoSexualCidadao, null: true)
      t.integer(:relacaoParentescoCidadao, null: true)
      t.integer(:situacaoMercadoTrabalhoCidadao, null: true)
      t.boolean(:statusDesejaInformarOrientacaoSexual, null: true)
      t.boolean(:statusFrequentaBenzedeira, null: true)
      t.boolean(:statusParticipaGrupoComunitario, null: true)
      t.boolean(:statusPossuiPlanoSaudePrivado, null: true)
      t.boolean(:statusTemAlgumaDeficiencia, null: true)
      t.integer(:identidadeGeneroCidadao, null: true)
      t.date(:dataObito, null: true)
      t.string(:numeroDO, null: true)
      t.boolean(:statusCadastroIndividualInativo, null: true)
      t.boolean(:statusGeradoAutomaticamente, null: true)
      t.boolean(:statusTermoRecusaCadastroIndividualAtencaoBasica, null: true, default: false)

      t.references(:doctor, null: false, foreign_key: true)

      t.timestamps
    end
  end
end
