#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative './cadastro_individual_types'

module Br
  module Gov
    module Saude
      module Esusab
        module Ras
          module Cadastroindividual
          end
        end
      end
    end
  end
end
