# frozen_string_literal: true
#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative './ficha_atendimento_individual_types'

module Br
  module Gov
    module Saude
      module Esusab
        module Ras
          module Atendindividual
          end
        end
      end
    end
  end
end
